### ISSUE TITLE
Support for Windows?

### ISSUE THREAD

**Issue by Cakedy** [NerdyPepper/scientifica#1]
I love the font running on my Linux laptop but I really wish if it can come to Windows as it appears to be an easy process. Is it coming anytime soon?

**Comment by NerdyPepper** [comment]
I have created a separate [branch](https://github.com/NerdyPepper/scientifica/tree/windows) with a ```.fon``` export.

It would be great to have some feedback/reviews as I don't have access to a Windows machine at the moment.

Cheers.

**Comment by Cakedy** [comment]
Ok so it kinda works but, in size 60 and 72, the font seems kinda stretched.
![image](https://user-images.githubusercontent.com/14469983/34071132-b64ba458-e23f-11e7-92b8-349c7096c8a6.png)

**Comment by NerdyPepper** [comment]
Bitmap fonts are not meant to be scaled. That is why you see distortion at sizes other than the original.

The preview window has the right size of this font.
