### ISSUE TITLE
Update bold style

### ISSUE THREAD

**Issue by NerdyPepper** [NerdyPepper/scientifica#10]
The current blocky style does not suit the font.

I have created a small caps version, to replace this 'bold' version.

Here are some previews:

![Preview 1](https://0x0.st/sBFy.png)
![Preview 2](https://0x0.st/sBdk.png)
![Preview 3](https://0x0.st/sBFJ.png)

Tell me what you think.

**Comment by The-Soulless** [comment]
I like it and prefer it. I never really thought that the bold fit with the font, to the point of thinking that my terminal was using the wrong font when it was bold.

**Comment by NerdyPepper** [comment]
@The-Soulless , the new version is being developed at the [small_caps](https://github.com/NerdyPepper/scientifica/tree/small_caps) branch.

**Comment by icyphox** [comment]
Ok

**Comment by The-Soulless** [comment]
After using it for a while, It's not as good as I previously believed, with the only difference between caps and lowercase letters being size, It makes it hard to tell if something is capitalized or not if it's either full caps or full lowercase.
