### ISSUE TITLE
Italic?

### ISSUE THREAD

**Issue by Cakedy** [NerdyPepper/scientifica#13]
Since curie has it, is it possible for scientifica to have it as well?

**Comment by NerdyPepper** [comment]
The original plan was to have blocky bold and small-caps italic.  
Maybe I could try a cursive style?  
There aren't many pixels to work with. Feel free to give suggestions!

**Comment by Cakedy** [comment]
Not sure how a cursive bitmap font would look like but I have a feeling that the small-caps italic idea might be good.

**Comment by NerdyPepper** [comment]
Cursive italics have been added.  
Tell me what you think!

![scrot](https://0x0.st/s1Jq.png)

**Comment by Cakedy** [comment]
It's really good but as @RewoundVHS said, the cursive captial isn't easily noticeable.

**Comment by NerdyPepper** [comment]
The capital letter `I` has been fixed. It looks better now imo. I am still working on adapting the other capital letters to cursive lettering.
