### ISSUE TITLE
Double-size font for retina screens

### ISSUE THREAD

**Issue by RedBeard0531** [NerdyPepper/scientifica#15]
The current font size is way too wee when used on a retina/HiDPI display.

**Comment by NerdyPepper** [comment]
If you have a Mac (retina display), use the `.dfont`.   
 If you have a 4k display, just use a regular font, these pixel fonts are meant to alleviate font rendering problems on low resolution displays.  
Or, as @RewoundVHS mentioned, try the doubler script.
