### ISSUE TITLE
text size in terminal

### ISSUE THREAD

**Issue by nawtrobar** [NerdyPepper/scientifica#17]
The font is much smaller in terminal windows than it is any other appIication. I suppose it may have something to do with resolution settings, but I really don't understand why it's happening. Hoping you might be able and willing to offer some insight. thanks.

**Comment by RewoundVHS** [comment]
Could you provide more details and screenshots? Which terminal emulator are you using?

**Comment by nawtrobar** [comment]
Also note that though my config says I set the pixel size to 13, I disabled scaling for bmp fonts before taking the screenshot.

**Comment by RewoundVHS** [comment]
The font used in the title bar and status bar is not scientifica. Look at the difference between lowercase i, lowercase n, capital B etc.

**Comment by nawtrobar** [comment]
OK. I guess it just fell back on a default then. Sorry. I suppose this is the appropriate size then and there's nothing I can do about it. Was hoping to be able to make a bit more legible. Any way thanks for taking your time.

**Comment by nawtrobar** [comment]
I'm mostly concerned with my terminal font at this point. I really like scientifica, but the size is a huge compromise. I'm not sure I understand that line from your config though.

**Comment by RewoundVHS** [comment]
That's what I was trying to say, the font in your terminal is scientifica, it is just a small font. The line from my config sets the default font for i3wm. You can try the doubler script included in the repository or try curie! https://github.com/NerdyPepper/curie

**Comment by nawtrobar** [comment]
okay. i just understand how you do that without the conventional format in i3, and also don't understand how you named the font. There aren't instructions for the double script. I'm assuming I compile an exectuable from it and run it in the folder?

**Comment by nawtrobar** [comment]
right. I just ran it. I installed the bdflib dependency, but the script still reports that it's missing. Thanks for your patience with this.

**Comment by RewoundVHS** [comment]
No big deal. I'd suggest just trying out curie. I'll have it up on the AUR within a few days.

**Comment by nawtrobar** [comment]
Unforutnately rxvt doesn't render all of the unicode characters that it had with scientifica. I should probably just switch terms.

**Comment by jandoerntlein** [comment]
Curie is (regardless of st or urxvt) still to small for a screen size of 3840x2160. Any chance that someone who got the doubler-script running can increase the size of Curie? Script fails for me on Ubuntu 16.04 (does not find bdflib although installed via pip).

**Comment by NerdyPepper** [comment]
@jandoerntlein @nawtrobar @cmcaine the font has successfully been doubled. 

You can find the `.bdf`s under the `doubled/` folder!
