### ISSUE TITLE
doubler.py doesn't seem to do anything

### ISSUE THREAD

**Issue by kepoorhampond** [NerdyPepper/scientifica#20]
So when I run doubler.py (which I assume is to systematically increase the size of the font), it doesn't ever get past this line:
```python
bdf = reader.read_bdf(sys.stdin)
```
It just holds and doesn't do anything. Am I missing something about how to run the program, or does it just take a long time?

Also, side note- I'm absolutely loving this font, the cursive for italics is my favorite thing ever, and I want to say thanks for continually working on it :)

**Comment by NerdyPepper** [comment]
To be honest, I haven't been able to work it either. Its just something I came across somewhere (don't remember where :/ ).

If you need a larger version, [curie](https://github.com/NerdyPepper/curie) is your only hope.

If you need something, feel free to ask!  
Cheers!

**Comment by csmcg** [comment]
Hi @kepoorhampond 
You need to redirect the contents of the font file into the script and then redirect the contents back out to another file which will hold the "doubled" data, like this: ``` python3 doubler.py < scientifica-11.bdf > scientifica-22.bdf ```

However, the script uses a library that seems to be pretty old, bdflib. I went through bdflib's ``` reader.py ``` and changed every instance of ``` iterable.next() ``` to ``` next(iterable) ``` and it works now. However, I don't think the script changes all of the metadata in the .bdf file. I'm working out how to do that now. If I figure it out, I'll post another issue or add it to one I previously opened [here](https://github.com/NerdyPepper/scientifica/issues/22).
