### ISSUE TITLE
Rendering issues in st

### ISSUE THREAD

**Issue by ma9e** [NerdyPepper/scientifica#21]
I'm not really clear on why this is happening, but st seems to be displaying scientifica glyphs twice as wide as they should be:

![double-space](https://user-images.githubusercontent.com/36235154/40148311-f3de7fe2-5932-11e8-8845-ba65520b7bd1.png)

I noticed that after opening and saving with `gbdfed`, the issue goes away:

![normal-space](https://user-images.githubusercontent.com/36235154/40148310-f3cd03e8-5932-11e8-8d48-2ceb359fd22b.png)

You can see what it does here: https://github.com/ma9e/scientifica/commit/bfa52a3d14c5dcf0975f0a1077072361b8bf15bc

So my hypothesis is that the bounding boxes are getting st confused. Not sure. Would you be opposed to just opening and saving all of the bdf files this way?  I haven't checked but I can't imagine it would affect the size of the compressed .pcf.gz files much.

**Comment by retipuj** [comment]
It's possible that your config may be causing this. I also use st, and never had such problem. [This](https://github.com/LukeSmithxyz/st) is the version that I'm using. Maybe you could try it out and see if the issue persists.
