### ISSUE TITLE
Is the font supposed to look like this?

### ISSUE THREAD

**Issue by Personinblack** [NerdyPepper/scientifica#23]
I just installed the font and the very thing I noticed is that the font looks completely different than how it looks in the screenshots on the readme page and r/unixporn. I don't know if I am doing something wrong. I installed it over the AUR (also tried installing manually) and followed the installation steps on the readme.md and this is how it looks on my urxvt:
![431](https://user-images.githubusercontent.com/24732321/40199201-68be474a-5a21-11e8-9e4f-904207d660c1.png)

For example the "a" is completely different.

**Comment by RewoundVHS** [comment]
You are correct, this font is not scientifica. Please post your urxvt config.

**Comment by Personinblack** [comment]
```
Xft.dpi: 96
Xft.antialias:  1
Xft.autohint:   0
Xft.hinting:    1
Xft.hintstyle:  hintslight
Xft.lcdfilter:  lcddefault
Xft.rgba: rgb

URxvt*internalBorder: 10
URxvt*externalBorder: 0
URxvt*urgentOnBell: true
URxvt*scrollTtyOutput: false
URxvt*scrollTtyKeypress: true

URxvt.font: xft:nerdypepper scientifica

URxvt*letterSpace: 1
URxvt*lineSpace: 0

URxvt*keysym.Control-Alt-c: 	perl:clipboard:copy
URxvt*keysym.Control-Alt-v:	perl:clipboard:pasteq
!URxvt*depth: 32

URxvt*saveLines: 			300000
URxvt*scrollBar: 			false
!URxvt*scrollstyle:			plain
URxvt*cursorBlink: 			true
URxvt*cursorUnderline: 		        true
URxvt*underlineURLs: false

URxvt*perl-lib: /usr/lib/urxvt/perl/
URxvt*perl-ext-common: default,matcher
URxvt*url-launcher: firefox
URxvt*matcher.button: 1

! Font-Size Keybindings !

URxvt.keysym.C-Up:     font-size:increase
URxvt.keysym.C-Down:   font-size:decrease
URxvt.keysym.C-S-Up:   font-size:incglobal
URxvt.keysym.C-S-Down: font-size:decglobal
URxvt.keysym.C-0:      font-size:reset
URxvt.keysym.C-space:  font-size:show

! Colors !

*.background:    [99]#100000
*.background2:   #100000
*.foreground:    #cf9a71
*.cursorColor:   #cf9a71

! Black
*.color8:        #100000
*.color0:        #1e0a0a

! Red
*.color9:        #8c2536
*.color1:        #6d1c2a

! Green
*.color10:       #608c55
*.color2:        #3a5433

! Yellow
*.color11:       #b38446
*.color3:        #9e743d

! Blue
*.color12:       #346399
*.color4:        #1d3654

! Magenta
*.color13:       #8c516e
*.color5:        #7d4963

! Cyan
*.color14:       #5c7b8c
*.color6:        #3b4f5a

! White
*.color15:       #cf9a71
*.color7:        #846248
```

**Comment by RewoundVHS** [comment]
I'm embarrassed, I double checked and this is in fact scientifica. The size and/or letter spacing are just off. Assuming you're using the AUR package, try adding the following to your .Xresources
URxvt.font: xft: nerdypepper scientifica:pixelsize=9
URxvt.letterSpace: 2

**Comment by Personinblack** [comment]
Changing the letter space makes it better but not the same as how it looks on the screenshots... The characters are different for sure. Look at this:
![432](https://user-images.githubusercontent.com/24732321/40206498-fd1df630-5a38-11e8-9cbc-ca90c2fc217b.png)
And this:
![433](https://i.redditmedia.com/jJx-7X-nLltUhIYJ_4VLAexqEtQwFBJ-OWk27FVtO5I.png?s=ffe821ed987d2f4b55308cde9bcad914)

**Comment by RewoundVHS** [comment]
Okay it appears to be displaying Gohufont for some reason. I was testing on my machine and it is doing the same thing. I use Termite and I've never had this issue before.

**Comment by Personinblack** [comment]
I don't think so... I tried GohuFont and it looked a bit different.

But this is definetely a problem with urxvt, just tried the font on the polybar and it looked how it should look without any problem. The weird thing is the screenshot above also uses urxvt and it displays the font correctly...

I think I should close this issue...
