### ISSUE TITLE
TrueType variant

### ISSUE THREAD

**Issue by deadcombo** [NerdyPepper/scientifica#25]
Do you have plans to make a .ttf variant of scientifica? I really like your font, and I would quite like to use it on my Android phone as well. I've grabbed the Niivu conversion, but that's a bit out of date and doesn't have the bold variant.

I would be happy to do it myself, but I don't know the first thing about manipulating fonts. If you have some pointers on what I should do to convert the font myself, I would really appreciate it.

**Comment by RewoundVHS** [comment]
This sounds like a good idea. I will get to work on this Monday.

**Comment by deadcombo** [comment]
That's good to hear! If there's anything I can do to help, just let me know.

**Comment by NerdyPepper** [comment]
I believe android typefaces need to have a minimum of 6 styles (including thin, extra thin)?

If so, it might not be possible, but Ill give it a go nevertheless.

The procedure is as follows (as explained by niivu):

>I extracted each characters bmp file converted them to a png. Multiplied the size of each character by 25 so each pixel equaled 25. Erased the white. Traced them back into the font editors ttf file.

Note that this requires each character to be extracted manually.

Scientifica regular ~500 chars  
Scientifica bold ~100 chars  
Scientifica cursive ~50 chars

**Comment by RewoundVHS** [comment]
NerdyPepper, I noticed you merged my .ttfs. These files were not functional at all, I meant to remove them from my fork after testing them but didn’t get the chance. I will issue a PR if I manage to get them to work. I’m sorry for any inconvenience/confusion.

**Comment by RewoundVHS** [comment]
By the way, the main issue I’m running into is with Autotrace in FontForge. I was attempting to use the script found here https://github.com/koemaeda/potrace-pixelperfect but the Autotrace function remains greyed our even after setting my environment variable to the script and selecting all glyphs.

**Comment by deadcombo** [comment]
Stupid question, do you have either the autotrace or the potrace packages installed? They don't come with FontForge. 

On June 11, 2018 3:32:36 PM GMT+01:00, Neve Laughery <notifications@github.com> wrote:
>By the way, the main issue I’m running into is with Autotrace in
>FontForge. I was attempting to use the script found here
>https://github.com/koemaeda/potrace-pixelperfect but the Autotrace
>function remains greyed our even after setting my environment variable
>to the script and selecting all glyphs.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/NerdyPepper/scientifica/issues/25#issuecomment-396264693

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RewoundVHS** [comment]
I installed Autotrace through the AUR package but I don’t have Potrace installed.

**Comment by deadcombo** [comment]
I would assume that you need to install potrace to run that script. There's a package in the AUR.

Then I guess you need to choose "prefer potrace" in the FontForge settings.

That's what I did this morning. 

On June 11, 2018 4:46:33 PM GMT+01:00, Neve Laughery <notifications@github.com> wrote:
>I installed Autotrace through the AUR package but I don’t have Potrace
>installed.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/NerdyPepper/scientifica/issues/25#issuecomment-396290414

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by deadcombo** [comment]
Oh, also, did you import the font on the background of a new file?

The autotrace function needs the font to be loaded in the background. 

On June 11, 2018 4:46:33 PM GMT+01:00, Neve Laughery <notifications@github.com> wrote:
>I installed Autotrace through the AUR package but I don’t have Potrace
>installed.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/NerdyPepper/scientifica/issues/25#issuecomment-396290414

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by deadcombo** [comment]
By using very basic FontForge scripting, I have extracted all glyphs into .png files. How would you prefer I share them?

**Comment by RewoundVHS** [comment]
You could create a fork and add the pngs to your repo! A moderately complex script could split and multiply the glyphs, removing the background could be done in GIMP.

**Comment by deadcombo** [comment]
[Here](https://github.com/deadcombo/scientifica) is my fork.

The files are under 'glyph_png', the script is called fontforge_export. My method is at the end of the README file.

Did you have any luck autotracing?

**Comment by deadcombo** [comment]
> I extracted each characters bmp file converted them to a png. Multiplied the size of each character by 25 so each pixel equaled 25. Erased the white. Traced them back into the font editors ttf file.

Multiplying and erasing is done. Already updated the files on the cloned repository. Using `imagemagick`, I did with these commands:

```
mogrify -transparent "#ffffff" *.png
mogrify -resize 2500% *.png

I am very unsure about the resize however. Are you sure they're supposed to be 25x bigger? Doing this to a .png distorts badly... If scaling is necessary, maybe this could be done with vector files instead?

(A note on the `mogrify` command: it modifies existing files directly. If you don't want this, use `convert` instead and pass an output argument.)

Anyway, I'd prefer to leave the autotracing to you if you don't mind, as I don't have any experience editing fonts.
```

**Comment by RewoundVHS** [comment]
Thank you so much for your work. I haven’t worked on tracing as I’ve been busy with classes and working on other parts of the project. I’ll get back to working on this over the weekend.

**Comment by outpoints** [comment]
Did you guys get anywhere? @deadcombo @RewoundVHS 
Trying to use this as my font in Command Prompt and it's messed up past 12px.
If there's anything I can do let me know :)

**Comment by NerdyPepper** [comment]
https://files.nerdypepper.me/x7.png

an attempt to autotrace scientifica using [bdf2ttf](https://github.com/dse/bdf2ttf) and [autotrace](https://github.com/autotrace/autotrace/).

**Comment by xxzozaxx** [comment]
Hellow @NerdyPepper, thanks for this awesome font.
I tried [BitsNPicas font converter](https://github.com/kreativekorp/bitsnpicas) and it seem to works. just need some final touch.

Could you try it plz.

**Comment by xxzozaxx** [comment]
![2019-11-01-104425_954x881_scrot](https://user-images.githubusercontent.com/20381921/68013087-af6c9900-fc94-11e9-8c41-46e2421c85db.png)
![2019-11-01-104449_954x881_scrot](https://user-images.githubusercontent.com/20381921/68013088-b0052f80-fc94-11e9-9548-a5dadafca325.png)
Here is the example

**Comment by NerdyPepper** [comment]
nice one @xxzozaxx! ill take a crack at this, and maybe, we can start shipping out rasterized vector fonts as well!

**Comment by alystair** [comment]
Any update re: Windows friendly fonts? Been a while

**Comment by NerdyPepper** [comment]
@alystair i did in fact get things to work with Bits 'n' Picas! Ill soon have a release containing `ttf` fonts

**Comment by NerdyPepper** [comment]
you can find the `ttf` variants under `/ttf`. i haven't tested to check if all characters render fine, but it looks good so far. give it a go and post your feedback in this thread!

 big thanks to @xxzozaxx for making this happen!

**Comment by alystair** [comment]
Cheers, tried them out. Seem to render with blurry edges

VSCode:

![image](https://user-images.githubusercontent.com/159109/78505931-9a64cc00-7744-11ea-9825-d8c349097a63.png)

![image](https://user-images.githubusercontent.com/159109/78505935-a2247080-7744-11ea-8976-c49dfc72db9a.png)

Illustrator (notice top edges):
![image](https://user-images.githubusercontent.com/159109/78505955-ae103280-7744-11ea-9aa6-2f39ff74ce60.png)

**Comment by NerdyPepper** [comment]
@alystair that is to be expected. the font will render "crispily" only at certain sizes, namely, 11px and multiples of 11px (provided your font rendering engine scales without interpolation).

**Comment by alystair** [comment]
Thanks. Wish fonts that are crisp only at specific intervals had a way of communicating it.. Only option would be as part of the font name right? E.g. Scientifica11

**Comment by NerdyPepper** [comment]
> Only option would be as part of the font name right?

Not really. Font rasterization is kind of an "inside" feature that the user shouldn't really be bothered about. Also, fonts may be rasterized at more than one size, Pragmata Pro, for example, provides crisp versions for all sizes from 9px through 14px.

Perhaps it would be best to simply mention it in the readme? 

Since the issue at hand as been addressed, I will be closing this issue (the `ttf` variant is ready to go), but feel free to continue discussion here.

**Comment by alystair** [comment]
Readme sounds good thanks!
