### ISSUE TITLE
Integer scaling

### ISSUE THREAD

**Issue by IronPiston** [NerdyPepper/scientifica#29]
Reading through other issues, the doubler.py script doesn't seem to work, and Curie is still too small on higher DPI displays(such as my ~109 DPI monitor). Would integer scaled versions for 2x, 3x, etc., be possible?

**Comment by NerdyPepper** [comment]
109 is not all that high. I currently use a doubled version of scientifica (just released, find it under the `doubled/` folder), and it is pretty big at 175dpi.

Give it a go and let me know, I can double curie as well if you need it.
