### ISSUE TITLE
Ligatures have spaces

### ISSUE THREAD

**Issue by its-suun** [NerdyPepper/scientifica#3]
<img src="https://u.teknik.io/OeNZu.png" align="left">Not sure if it's intended but the ligatures have spaces between the characters, which don't look so nice in my opinion. For example the left arrow ![](https://u.teknik.io/2Fkuy.png) has no space while the right arrow has one empty pixel ![](https://u.teknik.io/VqNIP.png).
The shown file is creep's [arrowtest.hs](https://github.com/romeovs/creep/blob/master/arrowtest.hs) using [creep.vim](https://github.com/romeovs/creep/blob/master/creep.vim).

**Comment by NerdyPepper** [comment]
I personally dont use ligatures because of inconsistencies.

I will surely look into this.

Did you notice these spaces in creep as well?

**Comment by its-suun** [comment]
Creep has it without spaces:
![](https://u.teknik.io/1vECm.png)

**Comment by NerdyPepper** [comment]
Alright, it looks like creep has inconsistent character bounding boxes, so it is able to _join_ the characters forming a ligature, by extending them beyond the grid lines.

Here's an example:

Creep:
![creeplig](https://user-images.githubusercontent.com/23743547/34651214-4daa2c2e-f3f3-11e7-9851-b0a86651897d.png)

Scientifica:
![scilig](https://user-images.githubusercontent.com/23743547/34651218-5894c766-f3f3-11e7-843c-6ba2bd188a7a.png)

I cannot extend the character in scientifica because it would break most linux terminals.

So, I have no solution to this issue as of now.

**Comment by its-suun** [comment]
Hmm, but why do some ligatures connect without an missing pixel, like the left arrow?

**Comment by NerdyPepper** [comment]
Every character in scientifica is like this:

4px character + 1px space

Some characters fill the entire 5 pixels, thereby touching the character to its *right*.

A 5px character followed by a 4px char will appear to be joint, whereas a 4px char followed by another character will have 1px space in between, which is what you are seeing.

Now, it is possible to make this 4px char wider by adding another pixel, for the sake of ligatures, but I personally am not a fan of symbols like equals and minus joining up.

Maybe I could export a separate version with 'ligatures enabled', which are basically certain characters occupying all 5 pixels.

**Comment by its-suun** [comment]
Would it then maybe be possible to create a special symbol, for example like the powerline arrow, which is a 5px wide minus sign?

**Comment by NerdyPepper** [comment]
Yeah sure. I can put them in the private use area block.

You could accordingly use them in the creep.vim plugin.

It should be up in the latest commit.

**Comment by its-suun** [comment]
Sorry for the long response time, i had to setup my system again.
The 5px wide minus sign works perfectly ![](https://u.teknik.io/h8re1.png) and the new arrow looks pretty nice too. But the equals sign is 1px too high:
![](https://u.teknik.io/Dyavk.png)
Also thanks for working on this, even tho you don't like ligatures :smile:

**Comment by NerdyPepper** [comment]
Thanks for pointing it out!

It should be fixed in the latest commit.

I'm glad you like it!
