### ISSUE TITLE
Small on high dpi

### ISSUE THREAD

**Issue by jonathandion** [NerdyPepper/scientifica#30]
Hi, `22px`works but it's still small on my screen :/ Can we make a 44px version for high dpi screen?

I guess all I need to do is to change all the 2 for 4 in `doubler.py` and run `py doubler.py` ?

Thanks and really nice font!

-----
**off topic** 
Color scheme from the screenshots?

**Comment by NerdyPepper** [comment]
Could you please share your display specs?  I cannot image using a 4x size on a screen that used to use size 11 fonts.

A 44px version shouldn't be hard to create. Ill create one soon.

Colorscheme: 

```
base00 #121c21
base01 #1e2e36
base02 #304b59
base03 #3f6173
base04 #7b8e98
base05 #aaafb2
base06 #bcd9e8
base07 #cfefff
base08 #f0696f
base09 #fa9a6a
base0A #f7cca1
base0B #76a08c
base0C #5f9993
base0D #718c97
base0E #ceb5ce
base0F #877366
```

This follows the base16 template.

**Comment by jonathandion** [comment]
3840x2160

**Comment by jonathandion** [comment]
Let me know what do to I can do it.

**Comment by NerdyPepper** [comment]
https://0x0.st/sWnf.bdf
https://0x0.st/sWnO.bdf
https://0x0.st/sWnV.bdf

Keep me updated!

**Comment by dieggsy** [comment]
@NerdyPepper where did you end up with this? Is a 44px font available/possible at the moment?

**Comment by NerdyPepper** [comment]
yes! producing 44px variants is fairly trivial. here you go:

regular `scientifica-44.bdf`:  
https://files.nerdypepper.me/RY.bdf

bold `scientificaBold-44.bdf`:  
https://files.nerdypepper.me/sB.bdf

italic `scientificaItalic-44.bdf`:  
https://files.nerdypepper.me/rs.bdf

**Comment by dieggsy** [comment]
@NerdyPepper huh - the script doesn't seem to be working for me:

```
$ python3 doubler.py < doubled/regular/scientifica-22.bdf > scientifica-44.bdf
Traceback (most recent call last):
  File "doubler.py", line 30, in <module>
    bdf = reader.read_bdf(sys.stdin)
  File "/usr/lib/python3.7/site-packages/bdflib/reader.py", line 124, in read_bdf
    assert next(iterable)[0] == b"ENDFONT"
StopIteration
```

And the files you provide for some reason aren't detected by `fc-cache -fv` even though the original files in the repo are.
