### ISSUE TITLE
Why the size of the fonts requires big increases to go from a size to a bigger size ?

### ISSUE THREAD

**Issue by cata0309** [NerdyPepper/scientifica#34]

**Comment by NerdyPepper** [comment]
The regular size uses a thickness of 1 pixel, the doubled size uses a thickness of 2 pixels. TTF file formats can use 1.5 pixels (by aliasing and a couple other techniques), which is not possible in bitmap fonts.

scientifica cannot be fractionally scaled, our scaling options are 2x, 3x, 4x etc.
