### ISSUE TITLE
Screenshots are dead.

### ISSUE THREAD

**Issue by fr3fou** [NerdyPepper/scientifica#35]
You should upload the images to github and use a relative path in your README.md such as
```
[image-alt-tag](screenshots/screenshot.png)
```
0x0 seems to have deleted the images, so they no longer show up in the README.md

**Comment by NerdyPepper** [comment]
will get on this later today.

**Comment by NerdyPepper** [comment]
https://nerdypepper.me/scientifica/

**Comment by alystair** [comment]
Hero image dead in readme

**Comment by NerdyPepper** [comment]
fixed @alystair!
