### ISSUE TITLE
fc-list recognize wrong scientificaItalic.ttf

### ISSUE THREAD

**Issue by haunt98** [NerdyPepper/scientifica#39]
scientificaItalic.ttf should show `scientifica:style=Italic` when `fc-list | grep scientifica`

![image](https://user-images.githubusercontent.com/5424272/79349870-f7405d80-7f60-11ea-810b-d3bb09cb1540.png)

**Comment by NerdyPepper** [comment]
That is very strange, because we faced the exact same issue once earlier. In any case, I have fixed this with the latest commit, I will make a release by the end of this week.

Thanks for bringing this to my notice!

**Comment by vaskark** [comment]
I have experienced the same with the italic version of scientifica. I'm on Ubuntu 19.10.
