### ISSUE TITLE
Powerline delimiter alignment

### ISSUE THREAD

**Issue by masaeedu** [NerdyPepper/scientifica#41]
Hello again. Not sure whether this is something that can be resolved for all sizes (I'm not super familiar with how fonts work), but I noticed that the powerline triangular delimiter thing doesn't quite fill its row at all sizes of the ttf font. In my Konsole setup, the glyph lines up perfectly at font size 8, but is slightly misaligned at larger sizes until it lined up again at 25 point size.

**Comment by masaeedu** [comment]
Here is a screen recording, hopefully that illustrates what I'm talking about:

https://masaeedu.s3.amazonaws.com/screencaps/github/scientifica/41/powerlinescaling.mp4

(sorry about the tiny size, please zoom in in the browser)

**Comment by NerdyPepper** [comment]
Unfortunately, there is nothing I can do about that, it lines up only at those sizes and multiples of those sizes.
