### ISSUE TITLE
Scientifica TTF not rendering correctly [Arch Linux]

### ISSUE THREAD

**Issue by candreslobor** [NerdyPepper/scientifica#46]
Greetings, I've installed the ttf version of scientifica. Since that the font is not rendering to well

[Screenshot](https://imgur.com/a/inyS6Lo)

As you can see the font doesn't look sharp, is more like blur

**Comment by NerdyPepper** [comment]
the ttf version will not be sharp unless you use a size which has a rasterized version, namely, 11 and multiples of 11. this size also, however, depends on your display dpi, so just mess around with sizes 7 to 11 and one of those should be sharp. if not, uninstall the ttf version, install the otb version, the otb comes with only one size, which is the sharp size.
