### ISSUE TITLE
Font doesn't work in kitty terminal

### ISSUE THREAD

**Issue by gwr-dasburo** [NerdyPepper/scientifica#49]
as the title says
i did all instructions in the install readme even tough it's a little out dated
i did `fc-list | grep scientifica`, it's all there
kitty works with other fonts
i got told that kitty expects to have spacing either 100 or 90 but scientifica has 110(?)
is there a workaround to make it work in kitty?

**Comment by NerdyPepper** [comment]
Kitty does not support bitmap fonts, see: https://github.com/kovidgoyal/kitty/issues/97, there is a workaround posted in the same thread, you can give that a go.

However, I would recommend installing the [TTF variants](https://github.com/NerdyPepper/scientifica/releases) (from the releases tab) and scaling it to 11 pt, the TTF font includes bitmap strikes at that size, so it should look identical to the OTB variant.

**Comment by kovasap** [comment]
I'm having this issue too.  What do you mean by "scaling it to 11 pt"?  How could I do that?

**Comment by NerdyPepper** [comment]
@kovasap install the TTF version and adjust the font size to 11pt.

**Comment by kovasap** [comment]
Right, how do I do that?  In kitty?  Or change the ttf file itself?

**Comment by NerdyPepper** [comment]
@kovasap yeah, changing the font size in kitty. You might have to play with the font size a bit till it displays the "rasterized" version (i. e., some sizes will look blurry, at a specific size, it will look sharp).

**Comment by kovasap** [comment]
My kitty config looks like:

```
font_family scientifica
font_size 11.0
```

but my font is not changing properly.  @gwr-dasburo what does your config look like?

**Comment by kovasap** [comment]
Any ideas here for how to make this config work?

**Comment by foofrog** [comment]
@kovasap, check if your font is listed in `kitty +list-fonts` by running the command. If not, then it may not be compatible with Kitty's rendering engine or may require additional configuration to work properly.

For this to work, the spacing of the font needs to be adjusted to `spacing=100` which could be done by creating a fontconfig. The following code can be added to `~/.config/fontconfig/fonts.conf`:
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
<match target="scan">
    <test name="family">
        <string>scientifica</string>
    </test>
    <edit name="spacing">
        <int>100</int>
    </edit>
</match>
</fontconfig>
```
Then run the following command to rebuild your fontconfig cache:
```sh
fc-cache -r
```
Now the font should be available in `kitty +list-fonts` and ready to be used with Kitty.
