### ISSUE TITLE
Inconsistent glyph for U+00DD LATIN CAPITAL LETTER Y WITH ACUTE

### ISSUE THREAD

**Issue by dscorbett** [NerdyPepper/scientifica#51]
The glyph for U+00DD LATIN CAPITAL LETTER Y WITH ACUTE lacks a pixel at the bottom right which U+0059 LATIN CAPITAL LETTER Y and other glyphs based on it have.
![ÝY](https://user-images.githubusercontent.com/1124347/110400779-40504300-8046-11eb-88c5-0ea0b6b27f72.png)

**Comment by NerdyPepper** [comment]
Good catch, should be fixed in the next release!
