### ISSUE TITLE
Wrong spacing for two Turkish characters

### ISSUE THREAD

**Issue by yigitsever** [NerdyPepper/scientifica#55]
First off, thank you for supporting Turkish character set :)

Turkish characters Ş (U+015E, Latin capital letter S with cedilla) and ğ (U+011F Latin small letter g with breve) display an unnecessary space after them, the rest of the Turkish character set are fine;

![image](https://user-images.githubusercontent.com/9094218/135608153-365e0c79-1f30-4d43-8ec9-fe8d427f5e4f.png)

Here's how it should look, using Noto Sans;

![image](https://user-images.githubusercontent.com/9094218/135608302-30fc194f-33b2-4033-aff8-3c61f4202161.png)

**Comment by NerdyPepper** [comment]
Thanks for the report! I'll take a look this weekend.

**Comment by dscorbett** [comment]
This is part of issue #47.

**Comment by NerdyPepper** [comment]
I am looking to fix this on a case by case basis. Most of the glyphs that have incorrect width metrics are a result of converting from creep's bounding box to a fixed bounding box.

**Comment by oppiliappan** [comment]
This specific issue has been fixed in the latest release.
