### ISSUE TITLE
Increase the size?

### ISSUE THREAD

**Issue by WarpspeedSCP** [NerdyPepper/scientifica#6]
When I try using scientifica on my terminal, it ends up looking tiny. Is there a way to increase the size of the font?

**Comment by flymia** [comment]
I would love that! It looks like such a cool font. But it's too small to use it on my X220 display.

**Comment by NerdyPepper** [comment]
A bigger version is in the works. But it will not maintain the *exact* character structure of the original.

Its about at big as [kakwafont](https://github.com/kakwa/kakwafont).

In the meanwhile, you could try to use the size [doubler](https://github.com/NerdyPepper/scientifica/blob/master/doubler.py) script (I have not been able to get it to work).

**Comment by NamedKitten** [comment]
When will a size doubled version of it be here?

**Comment by NerdyPepper** [comment]
@NamedKitten please do not ask for ETAs. I too have my own commitments.

If you are a fan of unfinished craftsmanship, here is a preview:  
Old to the left, and new to the right.
![early](https://u.teknik.io/ge3Hq.png)

[Here's](https://u.teknik.io/fJ76H.bdf
) the `.bdf`, but as I said, this font is not even close to complete (inconsistent spacing, lack of ligatures, etc.).  
You can try doubling it using the [doubler](https://github.com/NerdyPepper/scientifica/blob/master/doubler.py) script.

**Comment by topisani** [comment]
Curie looks nice! could you maybe set up a repo for it? I would like to help out a bit if possible

**Comment by Alucherdi** [comment]
> @NamedKitten please do not ask for ETAs. I too have my own commitments.
> 
> If you are a fan of unfinished craftsmanship, here is a preview:
> Old to the left, and new to the right.
> ![early](https://camo.githubusercontent.com/44b25b5119f669a3330e090cfa6f0531da536418/68747470733a2f2f752e74656b6e696b2e696f2f67653348712e706e67)
> 
> [Here's](https://u.teknik.io/fJ76H.bdf) the `.bdf` (the font id is `curie`), but as I said, this font is not even close to complete (inconsistent spacing, lack of ligatures, etc.).
> You can try doubling it using the [doubler](https://github.com/NerdyPepper/scientifica/blob/master/doubler.py) script.

Sorry about asking this but I have to know what Color Scheme are you using, please :(

**Comment by NerdyPepper** [comment]
@Alucherdi I created that color scheme myself, I am afraid those files are long gone :(
