### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by hasld** [NerdyPepper/scientifica#7]
Can we put the OFL [[1](http://scripts.sil.org/OFL "Open Font License")], an official FSF font license [[2](https://www.gnu.org/licenses/license-list.html#Fonts "FSF Font Licenses")] on the font? Heres what it gives as its overview:

> We want to:
>     enable others to participate in our projects
>     enable others to cater to needs for which we don't have the resources
>     share our wealth of knowledge and experience in the area of writing systems and pass on our tools
>     equip the community to meet its font needs

[1] http://scripts.sil.org/OFL

[2] https://www.gnu.org/licenses/license-list.html#Fonts

**Comment by NerdyPepper** [comment]
Sure!

Will look into this ASAP.
