### ISSUE TITLE
Create a way to import this via CSS

### ISSUE THREAD

**Issue by The-Soulless** [NerdyPepper/scientifica#9]
I would like to use scientifica on a webpage of mine as the default font, knowing not too many people will have scientifica installed I looked for a way to @import this but I didn't find any, could you create one or tell me another way?

**Comment by NerdyPepper** [comment]
Yeah, importing it will not work, websites have deprecated support for bitmap fonts.

[niivu](https://niivu.deviantart.com/) has exported the font to web compatible `.woff`. Grab the zip [here](https://niivu.deviantart.com/art/Scientifica-Font-732934778) (the button is at the top right). It should work like any other font. It contains only the basic ASCII charmap.

Expect to see a `.ttf` version of this font sometime later ;)
